# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import randomizer_pb2 as protos_dot_randomizer__pb2


class RandomizerServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRandomString = channel.unary_unary(
                '/randomizer.RandomizerService/GetRandomString',
                request_serializer=protos_dot_randomizer__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_randomizer__pb2.RandomStringResponse.FromString,
                )
        self.GetRandomUUIDStream = channel.unary_stream(
                '/randomizer.RandomizerService/GetRandomUUIDStream',
                request_serializer=protos_dot_randomizer__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_randomizer__pb2.RandomUUIDResponse.FromString,
                )
        self.GetArray = channel.unary_unary(
                '/randomizer.RandomizerService/GetArray',
                request_serializer=protos_dot_randomizer__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_randomizer__pb2.ArrayResponse.FromString,
                )
        self.GetArrayStream = channel.unary_stream(
                '/randomizer.RandomizerService/GetArrayStream',
                request_serializer=protos_dot_randomizer__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_randomizer__pb2.ArrayResponse.FromString,
                )


class RandomizerServiceServicer(object):
    """定义服务
    """

    def GetRandomString(self, request, context):
        """一元接口，返回一个随机字符串
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandomUUIDStream(self, request, context):
        """流接口，持续返回随机UUID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArray(self, request, context):
        """获取单个640x512的数组
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArrayStream(self, request, context):
        """获取640x512的数组流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RandomizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRandomString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomString,
                    request_deserializer=protos_dot_randomizer__pb2.Empty.FromString,
                    response_serializer=protos_dot_randomizer__pb2.RandomStringResponse.SerializeToString,
            ),
            'GetRandomUUIDStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRandomUUIDStream,
                    request_deserializer=protos_dot_randomizer__pb2.Empty.FromString,
                    response_serializer=protos_dot_randomizer__pb2.RandomUUIDResponse.SerializeToString,
            ),
            'GetArray': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArray,
                    request_deserializer=protos_dot_randomizer__pb2.Empty.FromString,
                    response_serializer=protos_dot_randomizer__pb2.ArrayResponse.SerializeToString,
            ),
            'GetArrayStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetArrayStream,
                    request_deserializer=protos_dot_randomizer__pb2.Empty.FromString,
                    response_serializer=protos_dot_randomizer__pb2.ArrayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'randomizer.RandomizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RandomizerService(object):
    """定义服务
    """

    @staticmethod
    def GetRandomString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/randomizer.RandomizerService/GetRandomString',
            protos_dot_randomizer__pb2.Empty.SerializeToString,
            protos_dot_randomizer__pb2.RandomStringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRandomUUIDStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/randomizer.RandomizerService/GetRandomUUIDStream',
            protos_dot_randomizer__pb2.Empty.SerializeToString,
            protos_dot_randomizer__pb2.RandomUUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/randomizer.RandomizerService/GetArray',
            protos_dot_randomizer__pb2.Empty.SerializeToString,
            protos_dot_randomizer__pb2.ArrayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArrayStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/randomizer.RandomizerService/GetArrayStream',
            protos_dot_randomizer__pb2.Empty.SerializeToString,
            protos_dot_randomizer__pb2.ArrayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
