# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rray.proto\x12\x05\x61rray\"\x07\n\x05\x45mpty\"\x1c\n\rArrayResponse\x12\x0b\n\x03row\x18\x01 \x03(\x02\x32v\n\x0c\x41rrayService\x12.\n\x08GetArray\x12\x0c.array.Empty\x1a\x14.array.ArrayResponse\x12\x36\n\x0eGetArrayStream\x12\x0c.array.Empty\x1a\x14.array.ArrayResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'array_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_ARRAYRESPONSE']._serialized_start=31
  _globals['_ARRAYRESPONSE']._serialized_end=59
  _globals['_ARRAYSERVICE']._serialized_start=61
  _globals['_ARRAYSERVICE']._serialized_end=179
# @@protoc_insertion_point(module_scope)
