# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: randomizer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10randomizer.proto\x12\nrandomizer\"\x07\n\x05\x45mpty\"%\n\x14RandomStringResponse\x12\r\n\x05value\x18\x01 \x01(\t\"\"\n\x12RandomUUIDResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t2\xa7\x01\n\x11RandomizerService\x12\x46\n\x0fGetRandomString\x12\x11.randomizer.Empty\x1a .randomizer.RandomStringResponse\x12J\n\x13GetRandomUUIDStream\x12\x11.randomizer.Empty\x1a\x1e.randomizer.RandomUUIDResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'randomizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_RANDOMSTRINGRESPONSE']._serialized_start=41
  _globals['_RANDOMSTRINGRESPONSE']._serialized_end=78
  _globals['_RANDOMUUIDRESPONSE']._serialized_start=80
  _globals['_RANDOMUUIDRESPONSE']._serialized_end=114
  _globals['_RANDOMIZERSERVICE']._serialized_start=117
  _globals['_RANDOMIZERSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
